In [1]:
import pandas as pd

df = pd.read_parquet(r"C:\Users\Акмира\OneDrive\Документы\GitHub\ICT_2022\data_streamers.parquet")
print(df)

    Time_of_the_day  Number_of_viewers  Average_age_of_viewers  \
0                10              23811                      20   
1                11              47309                      16   
2                 1              25461                      30   
3                14               9719                      29   
4                 2              30176                      14   
5                14               5560                      21   
6                 9              45401                       7   
7                 5              43503                      27   
8                 5              40367                      22   
9                 9              20385                      15   
10                0              26368                      28   
11                6               2429                      27   
12                6              29969                      27   
13               23              37973                      17   
14        

In [2]:
import numpy as np

x1 = df['Time_of_the_day'].to_numpy().reshape(-1, 1)
x2 = df['Number_of_viewers'].to_numpy().reshape(-1, 1)
x3 = df['Average_age_of_viewers'].to_numpy().reshape(-1, 1)

y = df['Video_game'].to_numpy().ravel()
print(x1)
print(x2)
print(x3)
print(y)


[[10]
 [11]
 [ 1]
 [14]
 [ 2]
 [14]
 [ 9]
 [ 5]
 [ 5]
 [ 9]
 [ 0]
 [ 6]
 [ 6]
 [23]
 [19]
 [19]
 [19]
 [ 2]
 [ 4]
 [19]
 [ 2]
 [18]
 [ 4]
 [15]
 [12]
 [22]
 [12]
 [ 4]
 [ 7]]
[[23811]
 [47309]
 [25461]
 [ 9719]
 [30176]
 [ 5560]
 [45401]
 [43503]
 [40367]
 [20385]
 [26368]
 [ 2429]
 [29969]
 [37973]
 [17662]
 [37070]
 [ 5146]
 [47057]
 [ 1423]
 [46764]
 [25286]
 [46267]
 [ 4617]
 [ 9894]
 [14649]
 [ 2477]
 [16949]
 [47644]
 [ 4693]]
[[20]
 [16]
 [30]
 [29]
 [14]
 [21]
 [ 7]
 [27]
 [22]
 [15]
 [28]
 [27]
 [27]
 [17]
 [12]
 [28]
 [26]
 [11]
 [19]
 [ 7]
 [25]
 [17]
 [26]
 [24]
 [23]
 [27]
 [30]
 [15]
 [13]]
['League of Legend' 'Fifa' 'Minecraft' 'Minecraft' 'Fifa'
 'League of Legend' 'GTA V' 'League of Legend' 'League of Legend'
 'League of Legend' 'Minecraft' 'Minecraft' 'Minecraft' 'Fifa' 'Fifa'
 'League of Legend' 'Minecraft' 'Fifa' 'Minecraft' 'GTA V' 'Minecraft'
 'Fifa' 'Minecraft' 'League of Legend' 'League of Legend' 'Minecraft'
 'Minecraft' 'Fifa' 'League of Legend']


In [6]:
import sklearn.model_selection as sksel
import sklearn.preprocessing as skprepro
import sklearn.linear_model as skmod

encoder = skprepro.LabelEncoder()
encoder = encoder.fit(y)
fav_code = encoder.transform(y)

print(fav_code)
print(encoder.classes_)

[2 0 3 3 0 2 1 2 2 2 3 3 3 0 0 2 3 0 3 1 3 0 3 2 2 3 3 0 2]
['Fifa' 'GTA V' 'League of Legend' 'Minecraft']


In [16]:

x = np.hstack([x1, x2, x3])

model = skmod.LogisticRegression(multi_class = 'ovr')
model = model.fit(x, fav_code)

print(model.score(x, fav_code))
print(x)

0.8620689655172413
[[   10 23811    20]
 [   11 47309    16]
 [    1 25461    30]
 [   14  9719    29]
 [    2 30176    14]
 [   14  5560    21]
 [    9 45401     7]
 [    5 43503    27]
 [    5 40367    22]
 [    9 20385    15]
 [    0 26368    28]
 [    6  2429    27]
 [    6 29969    27]
 [   23 37973    17]
 [   19 17662    12]
 [   19 37070    28]
 [   19  5146    26]
 [    2 47057    11]
 [    4  1423    19]
 [   19 46764     7]
 [    2 25286    25]
 [   18 46267    17]
 [    4  4617    26]
 [   15  9894    24]
 [   12 14649    23]
 [   22  2477    27]
 [   12 16949    30]
 [    4 47644    15]
 [    7  4693    13]]


In [25]:
print(model.predict_proba(np.array([[   11 ,10000 ,   18]])))
print(model.predict_proba(np.array([[   23 ,1000 ,   30]])))

print(encoder.classes_)

print(encoder.inverse_transform(model.predict(np.array([[   11 ,10000 ,   18]]))))
print(encoder.inverse_transform(model.predict(np.array([[   23 ,1000 ,   30]]))))
# print(encoder.inverse_transform(model.predict(np.array([[20], [30], [40]]))))
# print(model.predict_proba(np.array([[20], [30], [40]])))

[[1.26333295e-01 1.12704196e-05 4.64051373e-01 4.09604061e-01]]
[[1.09953053e-02 1.10048111e-09 3.36041953e-01 6.52962741e-01]]
['Fifa' 'GTA V' 'League of Legend' 'Minecraft']
['League of Legend']
['Minecraft']


In [32]:
# It should be before the creating model
yy = fav_code.reshape(-1, 1)
x_train, x_test, y_train, y_test = sksel.train_test_split(x, 
                                                          yy, 
                                                          train_size = 0.8,
                                                          shuffle = False)

scaler_x = skprepro.StandardScaler()
# scaler_y = skprepro.StandardScaler()
scaler_x = scaler_x.fit(x_train)
x_train_std = scaler_x.transform(x_train)
# y_train_std = scaler_y.fit_transform(y_train)
print(x_train_std)


[[ 0.05618858 -0.19820462 -0.06817978]
 [ 0.19978161  1.28813478 -0.63841068]
 [-1.2361487  -0.09383574  1.35739746]
 [ 0.6305607  -1.08957813  1.21483973]
 [-1.09255567  0.20440625 -0.92352612]
 [ 0.6305607  -1.35265097  0.07437794]
 [-0.08740445  1.1674464  -1.92143019]
 [-0.66177658  1.04739055  0.92972428]
 [-0.66177658  0.84902642  0.21693567]
 [-0.08740445 -0.41491237 -0.7809684 ]
 [-1.37974173 -0.03646448  1.07228201]
 [-0.51818355 -1.55069883  0.92972428]
 [-0.51818355  0.1913127   0.92972428]
 [ 1.92289798  0.69759666 -0.49585295]
 [ 1.34852586 -0.58715266 -1.20864157]
 [ 1.34852586  0.64047842  1.07228201]
 [ 1.34852586 -1.37883807  0.78716656]
 [-1.09255567  1.2721948  -1.35119929]
 [-0.80536961 -1.61433223 -0.2107375 ]
 [ 1.34852586  1.25366142 -1.92143019]
 [-1.09255567 -0.10490517  0.64460884]
 [ 1.20493282  1.22222425 -0.49585295]
 [-0.80536961 -1.41229937  0.78716656]]
