In [1]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

print(array)

[1 2 3 4 5 6]


In [2]:
l = [[1, 2, 3], [4, 5, 6]]
print(l)
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [3]:
l0 = [1, 2, 3]
l1 = l0.copy()
l1[0] = 55

print(l0)
print(l1)

[1, 2, 3]
[55, 2, 3]


In [6]:
arr0 = np.array([1, 2, 3])
arr1 = arr0.copy()

print(arr0)
print(arr1)

arr1[0] = 555

print(arr0)
print(arr1)

[1 2 3]
[1 2 3]
[1 2 3]
[555   2   3]


In [7]:
array = np.array([1, 2, 3, 4, 5])
print(array.shape)

(5,)


In [12]:
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((3, 2)))

[[1 2]
 [3 4]
 [5 6]]


In [13]:
array = np.array([1, 2, 3, 4, 5])
print(array.reshape((5, 1)))

[[1]
 [2]
 [3]
 [4]
 [5]]


In [17]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array.reshape((-1, 2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [30]:
array0 = np.array([1, 2, 3, 4, 5, 6])
array0 = (array0.reshape((-1, 2)))
array1 = np.array([7, 8, 9, 10, 11, 12])
array1 = (array1.reshape(-1, 2))

print(np.hstack([array0, array1]))

[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


In [26]:
a = np.array([1, 5, 9, 31, 45, 78])
print(a.reshape(3, 2))

[[ 1  5]
 [ 9 31]
 [45 78]]
